PAKISTAN_KEYWORDS = [
    # Pakistan-related news
    "pakistan",
    "pakistani",
    "pakistanis",
    # Pakistani-American identity and diaspora
    "pakistani american",
    "pakistani-american",
    "pakistani americans",
    "pakistani-americans",
    "pakistanis in america",
    "pakistanis in the us",
    "pakistanis in usa",
    "pakistani in america",
    "pakistani in the united states",
    "pakistan-born",
    "pakistani-born",
    "pakistani heritage",
    "pakistani diaspora",
    "pakistan diaspora",
    # Houston and Greater Houston community
    "pakistani houston",
    "houston pakistani",
    "pakistan houston",
    "houston pakistan",
    "pakistani sugar land",
    "sugar land pakistani",
    "pakistani katy",
    "katy pakistani",
    "pakistani stafford",
    "stafford pakistani",
    "pakistani pearland",
    "pearland pakistani",
    "pakistani cypress",
    "cypress pakistani",
    "pakistani the woodlands",
    "the woodlands pakistani",
    # Community and organizations
    "pakistani community",
    "pakistani communities",
    "pakistani immigrant",
    "pakistani immigrants",
    "pakistani community in america",
    "pakistani community in the us",
    "pakistani community in usa",
    "pakistani american",
    "pakistani diaspora",
    "appna",  # Huge Pakistani-American Physicians network
    "open global",  # Pakistani Entrepreneurs
    "pakistani students association",
    "pakistani american association",
    # Pakistani organizations
    "pakistani association",
    "pakistani american association",
    "pakistani organization",
    "pakistani community organization",
    "pakistani cultural association",
    "pakistani community center",
    "pakistani chamber",
    "pakistani business association",
    "pakistan association of greater houston",
    "pakistan association houston",
    "pagh",
    "pakistan consulate houston",
    "consulate general of pakistan",
    "isgh",
    "islamic society of greater houston",
    "pakistan independence celebration",
    # Pakistani students
    "pakistani student",
    "pakistani students",
    "pakistani student association",
    "pakistani student organization",
    "pakistani american students",
    # Pakistani professionals / businesses
    "pakistani business",
    "pakistani businesses",
    "pakistani entrepreneur",
    "pakistani entrepreneurs",
    "pakistani professional",
    "pakistani professionals",
    "pakistani doctor",
    "pakistani doctors",
    "pakistani lawyer",
    "pakistani lawyers",
    "pakistani engineer",
    "pakistani engineers",
    # Pakistani diplomatic presence in the U.S.
    "pakistan consulate",
    "consulate of pakistan",
    "pakistan embassy",
    "embassy of pakistan",
    # Pakistani cultural/community events
    "pakistani culture",
    "pakistani cultural",
    "pakistani festival",
    "pakistani celebration",
    "pakistani event",
    "pakistani community event",
    "pakistan independence day",
    "pakistan day",
    # Pakistani religious/community context
    "pakistani mosque",
    "pakistani islamic center",
    "pakistani muslim community",
    "pakistani eid",
    "pakistani ramadan",
    "pakistani iftar",
    # Pakistani food
    "pakistani restaurant",
    "pakistani restaurants",
    "pakistani food",
    # Pakistani sports in the U.S.
    "pakistani cricket",
    "pakistan cricket usa",
    "pakistani cricket usa",
    "pakistani cricketer",
    "pakistani cricketer usa",
    # U.S.–Pakistan community connection
    "pakistan usa community",
    "pakistan us community",
    "pakistan america community",
    "pakistani american community",
    "pakistani american diaspora",
    "pakistan american community",
]
