POTOHAR_KEYWORDS = [
    # Murree & Galyat Region
    "murree",
    "murree hills",
    "murree district",
    "murree tehsil",
    "galyat",
    "galiyat",
    "nathia gali",
    "nathiagali",
    "dunga gali",
    "changla gali",
    "khanspur",
    "ayubia",
    "ayubia national park",
    "bhurban",
    "patriata",
    "new murree",
    "upper topa",
    "lower topa",
    "ghora gali",
    "jhika gali",
    "kuldana",
    "kashmir point",
    "pindi point",
    "lawrence college",
    "mall road murree",
    "patriata chairlift",
    "murree expressway",
    "murree road",
    "murree administration",
    "assistant commissioner murree",
    "deputy commissioner murree",
    "murree police",
    "rescue 1122 murree",
    "gpo chowk",
    "kashmir road",
    "barian",
    "khaira gali",
    "bagnotar",
    "mukshpuri",
    "miranjani",
    "pipeline track",
    "mushkpuri top",
    "miranjani top",
    "green spot",
    "lalazar park",
    "galyat development authority",
    "gda",
    "galyat forest",
    # Islamabad Region
    "islamabad",
    "blue area",
    "red zone",
    "margalla hills",
    "pir sohawa",
    "faisal mosque",
    "rawal lake",
    "bani gala",
    "bhara kahu",
    "tarlai",
    "nilore",
    "capital development authority",
    "cda",
    "islamabad police",
    # Rawalpindi & Potohar Region
    "potohar",
    "pothohar",
    "potwar",
    "pothwar",
    "rawalpindi",
    "saddar",
    "raja bazaar",
    "committee chowk",
    "faizabad",
    "satellite town",
    "chaklala",
    "adiala",
    "bahria town",
    "dha rawalpindi",
    "gujar khan",
    "kahuta",
    "kallar syedan",
    "taxila",
    "wah cantt",
    "rawalpindi development authority",
    "rda",
    # Outer Districts
    "attock",
    "hazro",
    "hasan abdal",
    "fateh jang",
    "pindigheb",
    "jand",
    "kamra",
    "chakwal",
    "talagang",
    "kallar kahar",
    "choa saidan shah",
    "lawa",
    "dhudial",
    "katas raj",
    "jhelum",
    "dina",
    "sohawa",
    "pind dadan khan",
    "mangla",
    "mangla dam",
    "rohtas fort",
]
