POTOHAR_KEYWORDS = [
    "murree",
    "murree hills",
    "murree district",
    "murree tehsil",
    "galyat",
    "galiyat",
    "nathia gali",
    "nathiagali",
    "dunga gali",
    "changla gali",
    "khanspur",
    "ayubia",
    "ayubia national park",
    "bhurban",
    "patriata",
    "new murree",
    "upper topa",
    "lower topa",
    "ghora gali",
    "jhika gali",
    "kuldana",
    "kashmir point",
    "pindi point",
    "lawrence college",
    "mall road murree",
    "patriata chairlift",
    "patriata chair lift",
    "murree expressway",
    "murree road",
    "snowfall",
    "tourists",
    "tourism",
    "hotel",
    "guest house",
    "chairlift",
    "cable car",
    "murree administration",
    "assistant commissioner murree",
    "deputy commissioner murree",
    "murree police",
    "rescue 1122 murree",
    "gpo chowk",
    "kashmir road",
    "barian",
    "barian gali",
    "khaira gali",
    "bagnotar",
    "mukshpuri",
    "miranjani",
    "pipeline track",
    "mushkpuri top",
    "miranjani top",
    "murree nathia gali road",
    "nathia gali road",
    "green spot",
    "lalazar park",
    "ayubia chairlift",
    "ayubia chair lift",
    "galyat development authority",
    "gda",
    "tehsil murree",
    "galyat forest",
    "potohar",
    "pothohar",
    "potwar",
    "pothwar",
    "islamabad",
    "blue area",
    "red zone",
    "margalla hills",
    "pir sohawa",
    "faisal mosque",
    "rawal lake",
    "bani gala",
    "bhara kahu",
    "tarlai",
    "nilore",
    "rawalpindi",
    "saddar",
    "raja bazaar",
    "committee chowk",
    "faizabad",
    "satellite town",
    "chaklala",
    "adiala",
    "bahria town",
    "dha rawalpindi",
    "gujar khan",
    "kahuta",
    "kallar syedan",
    "taxila",
    "wah cantt",
    "attock",
    "hazro",
    "hasan abdal",
    "fateh jang",
    "pindigheb",
    "jand",
    "kamra",
    "chakwal",
    "talagang",
    "kallar kahar",
    "choa saidan shah",
    "lawa",
    "dhudial",
    "katas raj",
    "jhelum",
    "dina",
    "sohawa",
    "pind dadan khan",
    "mangla",
    "mangla dam",
    "rohtas fort",
]
