GOOGLE_NEWS_FEEDS = [
    "https://news.google.com/rss/search?q=Islamabad+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=CDA+Islamabad+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=Islamabad+Police+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=Islamabad+Traffic+Police+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=ICT+Administration+Islamabad+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=Islamabad+events+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=Islamabad+rain+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=Margalla+Hills+Islamabad+when:7d&hl=en-PK&gl=PK&ceid=PK:en",
]

GENERAL_NATIONAL_FEEDS = [
    "https://tribune.com.pk/feed/homepage",
    "https://www.thenews.com.pk/rss/1/1",
]

EMBASSY_NEWS_FEEDS = [
    "https://news.google.com/rss/search?q=%22U.S.+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22British+High+Commission%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Chinese+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Japanese+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22German+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22French+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22EU+Delegation%22+Pakistan+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Canadian+High+Commission%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Australian+High+Commission%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Turkish+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Saudi+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22UAE+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Qatari+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Iranian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Korean+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Indonesian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Malaysian+High+Commission%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Thai+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Danish+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Swedish+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Norwegian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Swiss+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Dutch+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Finnish+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Polish+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Austrian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Belgian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Czech+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Hungarian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Irish+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Greek+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Romanian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
    "https://news.google.com/rss/search?q=%22Italian+Embassy%22+Islamabad+when%3A7d&hl=en-PK&gl=PK&ceid=PK:en",
]