ISLAMABAD_KEYWORDS = [
    # Core
    "islamabad",
    "islamabad capital territory",
    # Government
    "capital development authority",
    "islamabad metropolitan corporation",
    "metropolitan corporation islamabad",
    "cabinet division",
    "capital administration and development division",
    "pak secretariat",
    "constitution avenue",
    "foreign office",
    "ministry of interior",
    "parliament house",
    "national assembly",
    "senate of pakistan",
    "president house",
    "prime minister house",
    "supreme court of pakistan",
    "islamabad high court",
    "election commission of pakistan",
    "nadra headquarters",
    "pta headquarters",
    "fbr headquarters",
    "planning commission",
    "pemra",
    "nepra",
    "ogra",
    # Police & Administration
    "islamabad police",
    "islamabad capital police",
    "traffic police islamabad",
    "ict police",
    "district administration islamabad",
    "deputy commissioner islamabad",
    "assistant commissioner islamabad",
    "safe city islamabad",
    "safe city authority",
    "rescue 1122 islamabad",
    "ctd islamabad",
    # Courts
    "islamabad high court",
    # Roads
    "jinnah avenue",
    "srinagar highway",
    "kashmir highway",
    "islamabad expressway",
    "margalla avenue",
    # Local Areas
    "bhara kahu",
    "bara kahu",
    "chak shahzad",
    "nilore",
    "tramri",
    "tarnol",
    "golra sharif",
    "sangjani",
    "bani gala",
    "banigala",
    "humak",
    "model town humak",
    "frash town",
    "lohi bher",
    "sihala",
    "rawal town",
    # Housing
    "dha islamabad",
    "gulberg greens islamabad",
    "gulberg residences",
    "bahria enclave",
    "naval anchorage",
    "park view city islamabad",
    "park enclave",
    "capital smart city",
    "top city islamabad",
    "mumtaz city",
    "cbr town",
    "media town",
    "korang town",
    "soan garden",
    "pwd housing society",
    # Landmarks
    "blue area islamabad",
    "red zone islamabad",
    "centaurus",
    "centaurus mall",
    "faisal mosque",
    "pakistan monument",
    "lok virsa",
    "diplomatic enclave",
    "saidpur village",
    "shakarparian",
    "fatima jinnah park",
    "f-9 park",
    "rose and jasmine garden",
    # Tourism
    "margalla hills",
    "margalla hills national park",
    "pir sohawa",
    "daman-e-koh",
    "rawal lake",
    "rawal dam",
    "lake view park",
    "monal",
    "monal islamabad",
    # Airport
    "islamabad international airport",
    "new islamabad airport",
    # Hospitals
    "pims hospital",
    "pakistan institute of medical sciences",
    "polyclinic hospital islamabad",
    "shifa international hospital",
    "federal general hospital",
    "capital hospital",
    "national institute of health",
    # Universities
    "national university of sciences and technology",
    "nust islamabad",
    "comsats islamabad",
    "international islamic university islamabad",
    "air university islamabad",
    "quaid-i-azam university",
    "fast islamabad",
    "riphah international university",
    "national university of modern languages",
    "capital university of science and technology",
    "bahria university islamabad",
    "foundation university",
    "allama iqbal open university",
    "national university of technology",
    # Transport
    "metro bus islamabad",
    "islamabad metro",
    "orange line metro",
    # Event venues
    "pak china friendship centre",
    "pak china friendship center",
    "jinnah convention centre",
    "jinnah convention center",
    "islamabad club",
    "serena islamabad",
    "marriott islamabad",
    "hotel margala",
    "safa gold mall",
    # Short/Sectors/Acronyms
    "ict",
    "cda",
    "ecp",
    "ihc",
    "nih",
    "numl",
    "cust",
    "pims",
    "f-5",
    "f-6",
    "f-7",
    "f-8",
    "f-9",
    "f-10",
    "f-11",
    "f-12",
    "g-5",
    "g-6",
    "g-7",
    "g-8",
    "g-9",
    "g-10",
    "g-11",
    "g-12",
    "g-13",
    "g-14",
    "g-15",
    "h-8",
    "h-9",
    "h-10",
    "h-11",
    "i-8",
    "i-9",
    "i-10",
    "i-11",
    "i-12",
    "d-12",
    "e-7",
    "e-8",
    "e-9",
    "e-11",
    "c-13",
    "7th avenue",
    "9th avenue",
    "park road",
    "lehtrar road",
    "lehtrar",
    "golra",
    "trail 3",
    "trail 5",
    "trail 6",
    "serena hotel",
    "lake view park",
    "margalla hills national park",
]
