ISLAMABAD_KEYWORDS = [
    # Core
    "islamabad",
    "islamabad capital territory",
    # Government
    "capital development authority",
    "islamabad metropolitan corporation",
    "metropolitan corporation islamabad",
    "cabinet division",
    "capital administration and development division",
    "pak secretariat",
    "constitution avenue",
    "foreign office",
    "ministry of interior",
    "parliament house",
    "national assembly",
    "senate of pakistan",
    "president house",
    "prime minister house",
    "supreme court of pakistan",
    "islamabad high court",
    "election commission of pakistan",
    "nadra headquarters",
    "pta headquarters",
    "fbr headquarters",
    "planning commission",
    "pemra",
    "nepra",
    "ogra",
    # Police & Administration
    "islamabad police",
    "islamabad capital police",
    "traffic police islamabad",
    "ict police",
    "district administration islamabad",
    "deputy commissioner islamabad",
    "assistant commissioner islamabad",
    "safe city islamabad",
    "safe city authority",
    "rescue 1122 islamabad",
    "ctd islamabad",
    # Courts
    "islamabad high court",
    # Roads
    "jinnah avenue",
    "srinagar highway",
    "kashmir highway",
    "islamabad expressway",
    "margalla avenue",
    # Local Areas
    "bhara kahu",
    "bara kahu",
    "chak shahzad",
    "nilore",
    "tramri",
    "tarnol",
    "golra sharif",
    "sangjani",
    "bani gala",
    "banigala",
    "humak",
    "model town humak",
    "frash town",
    "lohi bher",
    "sihala",
    "rawal town",
    # Housing
    "dha islamabad",
    "gulberg greens islamabad",
    "gulberg residences",
    "bahria enclave",
    "naval anchorage",
    "park view city islamabad",
    "park enclave",
    "capital smart city",
    "top city islamabad",
    "mumtaz city",
    "cbr town",
    "media town",
    "korang town",
    "soan garden",
    "pwd housing society",
    # Landmarks
    "blue area islamabad",
    "red zone islamabad",
    "centaurus",
    "centaurus mall",
    "faisal mosque",
    "pakistan monument",
    "lok virsa",
    "diplomatic enclave",
    "saidpur village",
    "shakarparian",
    "fatima jinnah park",
    "f-9 park",
    "rose and jasmine garden",
    # Tourism
    "margalla hills",
    "margalla hills national park",
    "pir sohawa",
    "daman-e-koh",
    "rawal lake",
    "rawal dam",
    "lake view park",
    "monal",
    "monal islamabad",
    # Airport
    "islamabad international airport",
    "new islamabad airport",
    # Hospitals
    "pims hospital",
    "pakistan institute of medical sciences",
    "polyclinic hospital islamabad",
    "shifa international hospital",
    "federal general hospital",
    "capital hospital",
    "national institute of health",
    # Universities
    "national university of sciences and technology",
    "nust islamabad",
    "comsats islamabad",
    "international islamic university islamabad",
    "air university islamabad",
    "quaid-i-azam university",
    "fast islamabad",
    "riphah international university",
    "national university of modern languages",
    "capital university of science and technology",
    "bahria university islamabad",
    "foundation university",
    "allama iqbal open university",
    "national university of technology",
    # Transport
    "metro bus islamabad",
    "islamabad metro",
    "orange line metro",
    # Event venues
    "pak china friendship centre",
    "pak china friendship center",
    "jinnah convention centre",
    "jinnah convention center",
    "islamabad club",
    "serena islamabad",
    "marriott islamabad",
    "hotel margala",
    "safa gold mall",
    # Short/Sectors/Acronyms
    "ict",
    "cda",
    "ecp",
    "ihc",
    "nih",
    "numl",
    "cust",
    "pims",
    "f-5",
    "f-6",
    "f-7",
    "f-8",
    "f-9",
    "f-10",
    "f-11",
    "f-12",
    "g-5",
    "g-6",
    "g-7",
    "g-8",
    "g-9",
    "g-10",
    "g-11",
    "g-12",
    "g-13",
    "g-14",
    "g-15",
    "h-8",
    "h-9",
    "h-10",
    "h-11",
    "i-8",
    "i-9",
    "i-10",
    "i-11",
    "i-12",
    "d-12",
    "e-7",
    "e-8",
    "e-9",
    "e-11",
    "c-13",
    "7th avenue",
    "9th avenue",
    "park road",
    "lehtrar road",
    "lehtrar",
    "golra",
    "trail 3",
    "trail 5",
    "trail 6",
    "serena hotel",
    "lake view park",
    "margalla hills national park",
]
EMBASSY_KEYWORDS = [
    # United States
    "U.S. Embassy Islamabad",
    "US Embassy Islamabad",
    "U.S. Embassy in Islamabad",
    "US Embassy in Islamabad",
    "U.S Embassy Islamabad",
    "US Embassy Islamabad",
    "American Embassy Islamabad",
    "American Embassy in Islamabad",
    "US Embassy Pakistan",
    "U.S. Embassy Pakistan",
    "American Embassy Pakistan",
    # United Kingdom
    "British High Commission Islamabad",
    "British High Commission in Islamabad",
    "British Embassy Islamabad",
    "British Embassy in Islamabad",
    "UK High Commission Islamabad",
    "UK High Commission in Islamabad",
    "British High Commission Pakistan",
    "UK High Commission Pakistan",
    # China
    "Chinese Embassy Islamabad",
    "Chinese Embassy in Islamabad",
    "Embassy of China Islamabad",
    "Embassy of the People's Republic of China Islamabad",
    "Chinese Embassy Pakistan",
    "China Embassy Islamabad",
    # Japan
    "Japanese Embassy Islamabad",
    "Japanese Embassy in Islamabad",
    "Embassy of Japan Islamabad",
    "Embassy of Japan in Islamabad",
    "Japanese Embassy Pakistan",
    # Germany
    "German Embassy Islamabad",
    "German Embassy in Islamabad",
    "Embassy of Germany Islamabad",
    "Embassy of Germany in Islamabad",
    "German Embassy Pakistan",
    # France
    "French Embassy Islamabad",
    "French Embassy in Islamabad",
    "Embassy of France Islamabad",
    "Embassy of France in Islamabad",
    "French Embassy Pakistan",
    # European Union
    "EU Delegation Pakistan",
    "EU Delegation Islamabad",
    "European Union Delegation Pakistan",
    "European Union Delegation Islamabad",
    "Delegation of the European Union to Pakistan",
    "EU Mission Pakistan",
    "European Union Pakistan",
    # Canada
    "Canadian High Commission Islamabad",
    "Canadian High Commission in Islamabad",
    "Canadian Embassy Islamabad",
    "Canadian Embassy in Islamabad",
    "High Commission of Canada Islamabad",
    "Canada High Commission Islamabad",
    "Canadian High Commission Pakistan",
    # Australia
    "Australian High Commission Islamabad",
    "Australian High Commission in Islamabad",
    "Australian Embassy Islamabad",
    "Australian Embassy in Islamabad",
    "High Commission of Australia Islamabad",
    "Australian High Commission Pakistan",
    # Türkiye
    "Turkish Embassy Islamabad",
    "Turkish Embassy in Islamabad",
    "Embassy of Türkiye Islamabad",
    "Embassy of Turkey Islamabad",
    "Embassy of Türkiye in Islamabad",
    "Turkish Embassy Pakistan",
    "Turkey Embassy Islamabad",
    # Saudi Arabia
    "Saudi Embassy Islamabad",
    "Saudi Embassy in Islamabad",
    "Embassy of Saudi Arabia Islamabad",
    "Embassy of Saudi Arabia in Islamabad",
    "Saudi Arabian Embassy Islamabad",
    "Saudi Embassy Pakistan",
    # United Arab Emirates
    "UAE Embassy Islamabad",
    "UAE Embassy in Islamabad",
    "Embassy of UAE Islamabad",
    "Embassy of the United Arab Emirates Islamabad",
    "UAE Embassy Pakistan",
    "United Arab Emirates Embassy Islamabad",
    # Qatar
    "Qatari Embassy Islamabad",
    "Qatari Embassy in Islamabad",
    "Qatar Embassy Islamabad",
    "Qatar Embassy in Islamabad",
    "Embassy of Qatar Islamabad",
    "Embassy of Qatar in Islamabad",
    "Qatari Embassy Pakistan",
    # Iran
    "Iranian Embassy Islamabad",
    "Iranian Embassy in Islamabad",
    "Iran Embassy Islamabad",
    "Iran Embassy in Islamabad",
    "Embassy of Iran Islamabad",
    "Embassy of Iran in Islamabad",
    "Iranian Embassy Pakistan",
    # South Korea
    "Korean Embassy Islamabad",
    "Korean Embassy in Islamabad",
    "South Korean Embassy Islamabad",
    "South Korean Embassy in Islamabad",
    "Embassy of South Korea Islamabad",
    "Embassy of the Republic of Korea Islamabad",
    "Korean Embassy Pakistan",
    # Indonesia
    "Indonesian Embassy Islamabad",
    "Indonesian Embassy in Islamabad",
    "Embassy of Indonesia Islamabad",
    "Embassy of Indonesia in Islamabad",
    "Indonesian Embassy Pakistan",
    # Malaysia
    "Malaysian High Commission Islamabad",
    "Malaysian High Commission in Islamabad",
    "Malaysian Embassy Islamabad",
    "Malaysian Embassy in Islamabad",
    "High Commission of Malaysia Islamabad",
    "Malaysian High Commission Pakistan",
    # Thailand
    "Thai Embassy Islamabad",
    "Thai Embassy in Islamabad",
    "Embassy of Thailand Islamabad",
    "Embassy of Thailand in Islamabad",
    "Thai Embassy Pakistan",
    # Denmark
    "Danish Embassy Islamabad",
    "Danish Embassy in Islamabad",
    "Embassy of Denmark Islamabad",
    "Embassy of Denmark in Islamabad",
    "Danish Embassy Pakistan",
    # Sweden
    "Swedish Embassy Islamabad",
    "Swedish Embassy in Islamabad",
    "Embassy of Sweden Islamabad",
    "Embassy of Sweden in Islamabad",
    "Swedish Embassy Pakistan",
    # Norway
    "Norwegian Embassy Islamabad",
    "Norwegian Embassy in Islamabad",
    "Embassy of Norway Islamabad",
    "Embassy of Norway in Islamabad",
    "Norwegian Embassy Pakistan",
    # Switzerland
    "Swiss Embassy Islamabad",
    "Swiss Embassy in Islamabad",
    "Embassy of Switzerland Islamabad",
    "Embassy of Switzerland in Islamabad",
    "Swiss Embassy Pakistan",
    # Netherlands
    "Dutch Embassy Islamabad",
    "Dutch Embassy in Islamabad",
    "Netherlands Embassy Islamabad",
    "Netherlands Embassy in Islamabad",
    "Embassy of the Netherlands Islamabad",
    "Embassy of Netherlands Islamabad",
    "Dutch Embassy Pakistan",
    # Finland
    "Finnish Embassy Islamabad",
    "Finnish Embassy in Islamabad",
    "Embassy of Finland Islamabad",
    "Embassy of Finland in Islamabad",
    "Finnish Embassy Pakistan",
    # Poland
    "Polish Embassy Islamabad",
    "Polish Embassy in Islamabad",
    "Embassy of Poland Islamabad",
    "Embassy of Poland in Islamabad",
    "Polish Embassy Pakistan",
    # Austria
    "Austrian Embassy Islamabad",
    "Austrian Embassy in Islamabad",
    "Embassy of Austria Islamabad",
    "Embassy of Austria in Islamabad",
    "Austrian Embassy Pakistan",
    # Belgium
    "Belgian Embassy Islamabad",
    "Belgian Embassy in Islamabad",
    "Embassy of Belgium Islamabad",
    "Embassy of Belgium in Islamabad",
    "Belgian Embassy Pakistan",
    # Czech Republic
    "Czech Embassy Islamabad",
    "Czech Embassy in Islamabad",
    "Embassy of the Czech Republic Islamabad",
    "Embassy of the Czech Republic in Islamabad",
    "Czech Embassy Pakistan",
    # Hungary
    "Hungarian Embassy Islamabad",
    "Hungarian Embassy in Islamabad",
    "Embassy of Hungary Islamabad",
    "Embassy of Hungary in Islamabad",
    "Hungarian Embassy Pakistan",
    # Ireland
    "Irish Embassy Islamabad",
    "Irish Embassy in Islamabad",
    "Embassy of Ireland Islamabad",
    "Embassy of Ireland in Islamabad",
    "Irish Embassy Pakistan",
    # Greece
    "Greek Embassy Islamabad",
    "Greek Embassy in Islamabad",
    "Embassy of Greece Islamabad",
    "Embassy of Greece in Islamabad",
    "Greek Embassy Pakistan",
    # Romania
    "Romanian Embassy Islamabad",
    "Romanian Embassy in Islamabad",
    "Embassy of Romania Islamabad",
    "Embassy of Romania in Islamabad",
    "Romanian Embassy Pakistan",
    # Italy
    "Italian Embassy Islamabad",
    "Italian Embassy in Islamabad",
    "Embassy of Italy Islamabad",
    "Embassy of Italy in Islamabad",
    "Italian Embassy Pakistan",
]
# EMBASSY_KEYWORDS = [
#     "U.S. Embassy Islamabad",
#     "US Embassy Islamabad",
#     "American Embassy Islamabad",
#     "British High Commission Islamabad",
#     "British Embassy Islamabad",
#     "Chinese Embassy Islamabad",
#     "Japanese Embassy Islamabad",
#     "German Embassy Islamabad",
#     "French Embassy Islamabad",
#     "EU Delegation Pakistan",
#     "European Union Delegation Pakistan",
#     "Canadian High Commission Islamabad",
#     "Canadian Embassy Islamabad",
#     "Australian High Commission Islamabad",
#     "Australian Embassy Islamabad",
#     "Turkish Embassy Islamabad",
#     "Saudi Embassy Islamabad",
#     "UAE Embassy Islamabad",
#     "Qatari Embassy Islamabad",
#     "Qatar Embassy Islamabad",
#     "Iranian Embassy Islamabad",
#     "Iran Embassy Islamabad",
#     "Korean Embassy Islamabad",
#     "South Korean Embassy Islamabad",
#     "Indonesian Embassy Islamabad",
#     "Malaysian High Commission Islamabad",
#     "Malaysian Embassy Islamabad",
#     "Thai Embassy Islamabad",
#     "Danish Embassy Islamabad",
#     "Swedish Embassy Islamabad",
#     "Norwegian Embassy Islamabad",
#     "Swiss Embassy Islamabad",
#     "Dutch Embassy Islamabad",
#     "Netherlands Embassy Islamabad",
#     "Finnish Embassy Islamabad",
#     "Polish Embassy Islamabad",
#     "Austrian Embassy Islamabad",
#     "Belgian Embassy Islamabad",
#     "Czech Embassy Islamabad",
#     "Hungarian Embassy Islamabad",
#     "Irish Embassy Islamabad",
#     "Greek Embassy Islamabad",
#     "Romanian Embassy Islamabad",
#     "Italian Embassy Islamabad",
# ]
