SITE_CLEANUP_SELECTORS = {
    "app.com.pk": [
        ".jeg_share_button",
        ".jeg_meta_container",
        ".jeg_post_tags",
        ".jeg_postblock",
        ".jeg_ad",
        ".jeg_sidebar",
        ".sharedaddy",
        ".author-box",
        # Extra
        ".jeg_meta_date",
        ".jeg_meta_author",
        ".jeg_post_meta",
        ".post-meta",
        ".entry-meta",
        ".author",
        ".date",
        ".post-date",
        ".related-posts",
        ".related-news",
        ".social-share",
    ],
    "urdupoint.com": [
        ".news-author",
        ".news-date",
        ".social-icons",
        ".related-news",
        ".sidebar",
        ".tags",
        ".ads",
        ".news-detail-info",
        ".article-info",
        ".post-meta",
        ".entry-meta",
        ".author-detail",
        "i[aria-label='Published Time']",
    ],
    "tribune.com.pk": [
        ".story__meta",
        ".story__sidebar",
        ".story__tags",
        ".story__related",
        ".sidebar",
        ".advertisement",
    ],
    "dawn.com": [
        ".story__meta",
        ".story__sidebar",
        ".story__tags",
        ".story__related",
        ".sidebar",
        ".advertisement",
    ],
    "thenews.com.pk": [
        ".newsauthor",
        ".newsdate",
        ".relatednews",
        ".tags",
        ".advertisement",
        ".sidebar",
    ],
    "nation.com.pk": [
        ".author-box",
        ".post-meta",
        ".post-tags",
        ".social-share",
        ".related-posts",
        ".advertisement",
        ".sidebar",
    ],
    "dailytimes.com.pk": [
        ".post-meta",
        ".entry-meta",
        ".td-post-author-name",
        ".td-post-date",
        ".td-post-sharing",
        ".post-tags",
        ".sharedaddy",
        ".related-posts",
        ".advertisement",
    ],
    "dailyindependent.com.pk": [
        # Meta
        ".post-meta",
        ".entry-meta",
        ".td-post-meta",
        ".td-module-meta-info",
        ".jeg_meta_container",
        # Author / Date
        ".author",
        ".author-box",
        ".author-name",
        ".post-author",
        ".post-date",
        ".entry-date",
        ".published",
        ".byline",
        "time",
        # Share
        ".sharedaddy",
        ".social-share",
        ".share-buttons",
        # Related
        ".related-posts",
        ".related-news",
        ".post-tags",
        # Sidebar / Ads
        ".sidebar",
        ".widget",
        ".advertisement",
    ],
    "www.malaysiasun.com": [
        ".post-meta",
        ".entry-meta",
        ".author",
        ".author-box",
        ".byline",
        ".published",
        ".article-meta",
        ".article-info",
        ".story-meta",
        ".story-info",
        ".social-share",
        ".share-buttons",
        ".related-posts",
        ".related-news",
        ".sidebar",
        ".advertisement",
        "time",
    ],
}
