PESHAWAR_KEYWORDS = [
    "peshawar",
    "peshawar city",
    "peshawar district",
    "district peshawar",
    "city of peshawar",
    "capital city peshawar",
    "provincial capital peshawar",
    "peshawar capital",

    "hayatabad",
    "hayatabad peshawar",
    "university town",
    "university town peshawar",
    "university road peshawar",
    "board bazaar peshawar",
    "saddar peshawar",
    "cantt peshawar",
    "peshawar cantt",
    "karkhano",
    "karkhano market",
    "karkhano peshawar",
    "ring road peshawar",
    "peshawar ring road",
    "warsak road peshawar",
    "warsak peshawar",
    "nasir bagh",
    "nasir bagh road peshawar",
    "dalazak road peshawar",
    "kohat road peshawar",
    "charsadda road peshawar",
    "nowshera road peshawar",
    "gt road peshawar",
    "jamrud road peshawar",
    "bara road peshawar",
    "grand trunk road peshawar",
    "gulbahar peshawar",
    "hashtnagri peshawar",
    "karimabad peshawar",
    "fakirabad peshawar",
    "gulberg peshawar",
    "tehkal peshawar",
    "regi model town",
    "regi model town peshawar",
    "badaber peshawar",
    "mattani peshawar",
    "badhaber peshawar",
    "chamkani peshawar",
    "pajaggi road peshawar",
    "shah alam peshawar",
    "lahori gate peshawar",
    "kohati gate peshawar",
    "kabuli gate peshawar",
    "hashtnagri gate peshawar",

    "bala hisar fort",
    "bala hisar fort peshawar",
    "peshawar zoo",
    "peshawar museum",
    "qissa khwani bazaar",
    "qissa khwani peshawar",
    "mahasud bazaar peshawar",
    "shoba bazaar peshawar",
    "andarkhan peshawar",
    "namak mandi peshawar",
    "karim pura peshawar",

    "peshawar administration",
    "peshawar district administration",
    "district administration peshawar",
    "deputy commissioner peshawar",
    "dc peshawar",
    "commissioner peshawar",
    "peshawar commissioner",
    "assistant commissioner peshawar",
    "ac peshawar",
    "peshawar deputy commissioner",
    "peshawar district government",
    "peshawar local government",
    "peshawar municipal",
    "peshawar municipality",
    "tehsil peshawar",
    "peshawar tehsil",
    "peshawar development authority",
    "pda peshawar",

    "peshawar police",
    "police peshawar",
    "peshawar police chief",
    "ccpo peshawar",
    "ccpo peshawar police",
    "capital city police peshawar",
    "capital city police",
    "peshawar traffic police",
    "traffic police peshawar",
    "peshawar traffic",
    "peshawar crime",
    "crime in peshawar",
    "peshawar security",
    "security in peshawar",
    "peshawar law and order",
    "law and order peshawar",

    "peshawar high court",
    "phc peshawar",
    "peshawar high court bench",
    "peshawar bench",
    "high court peshawar",
    "peshawar judiciary",
    "peshawar court",
    "peshawar courts",

    "peshawar airport",
    "bacha khan international airport",
    "bacha khan airport",
    "peshawar international airport",
    "peshawar bus",
    "peshawar transport",
    "peshawar public transport",
    "peshawar roads",
    "peshawar road",
    "peshawar motorway",
    "peshawar motorway interchange",
    "peshawar bus rapid transit",
    "peshawar brt",
    "brt peshawar",
    "transpeshawar",
    "trans peshawar",
    "zu peshawar",
    "zu bus peshawar",

    "university of peshawar",
    "uop",
    "uop peshawar",
    "engineering university peshawar",
    "uet peshawar",
    "khyber medical university",
    "kmu peshawar",
    "islamia college peshawar",
    "islamia college university peshawar",
    "agriculture university peshawar",
    "abdul wali khan university peshawar",
    "iqra national university peshawar",
    "cecos university peshawar",
    "peshawar university",
    "peshawar school",
    "peshawar college",
    "peshawar education",
    "education in peshawar",
    "peshawar board",
    "bise peshawar",
    "board of intermediate and secondary education peshawar",

    "lady reading hospital",
    "lady reading hospital peshawar",
    "lrh peshawar",
    "khyber teaching hospital",
    "khyber teaching hospital peshawar",
    "kth peshawar",
    "hayatabad medical complex",
    "hayatabad medical complex peshawar",
    "hmc peshawar",
    "peshawar institute of cardiology",
    "pic peshawar",
    "institute of kidney diseases peshawar",
    "peshawar hospital",
    "hospitals in peshawar",
    "health peshawar",
    "healthcare peshawar",
    "medical peshawar",

    "khyber pakhtunkhwa",
    "khyber pakhtun khwa",
    "khyber pakhtunkhwa province",
    "khyber pakhtunkhwa government",
    "government of khyber pakhtunkhwa",
    "kp government",
    "kp govt",
    "kpk government",
    "kpk govt",
    "kp",
    "kpk",

    "kp assembly",
    "khyber pakhtunkhwa assembly",
    "provincial assembly kp",
    "kp cabinet",
    "kp provincial cabinet",
    "kp chief minister",
    "chief minister kp",
    "chief minister khyber pakhtunkhwa",
    "cm kp",
    "cm khyber pakhtunkhwa",
    "governor kp",
    "governor khyber pakhtunkhwa",
    "kp governor",
    "kp ministers",
    "kp minister",
    "kp provincial minister",
    "kp government departments",
    "kp development projects",
    "kp budget",
    "khyber pakhtunkhwa budget",
    "kp development budget",
    "kp legislation",
    "kp policy",

    "kp police",
    "khyber pakhtunkhwa police",
    "kpk police",
    "kp police chief",
    "ig kp police",
    "inspector general kp",
    "kp law and order",
    "khyber pakhtunkhwa law and order",
    "kp security",
    "khyber pakhtunkhwa security",
    "kp counter terrorism",
    "ctd kp",
    "counter terrorism department kp",

    "kp development",
    "khyber pakhtunkhwa development",
    "kp infrastructure",
    "kp roads",
    "kp highways",
    "kp electricity",
    "kp energy",
    "kp water",
    "kp health",
    "kp education",
    "kp hospitals",
    "kp schools",
    "kp universities",
    "kp public service",
    "kp government project",
    "kp development project",

    "kp economy",
    "khyber pakhtunkhwa economy",
    "kp business",
    "business in kp",
    "kp industries",
    "khyber pakhtunkhwa industries",
    "kp investment",
    "kp investors",
    "kp trade",
    "kp tourism",
    "khyber pakhtunkhwa tourism",

]