SKIP_DOMAINS = {
    "bdcrictime.com",
    "www.bdcrictime.com",
    "urdupoint.com",
    "www.urdupoint.com",
    "app.com.pk",
    "www.app.com.pk",
    # "urdupoint.com",
    # "malaysiasun.com",
    # "www.malaysiasun.com",
    # "fotmob.com",
    # "www.fotmob.com",
    # "mettisglobal.news",
    # "www.mettisglobal.news",
    # "app.com.pk",
    # "voicepk.net",
    # "www.voicepk.net",
    # "balochistanpulse.com",
    # "www.balochistanpulse.com",
    # "ndtv.com",
    # "www.ndtv.com",
    # "thestatesman.com",
    # "www.thestatesman.com",
    # "newsonair.gov.in",
    # "www.newsonair.gov.in",
    # "cricinfo.com",
    # "www.cricinfo.com",
}
